apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
  namespace: ngk8ht
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: myk8sauth
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: authsec
        property: password
